name: 🐛 Bug Report
description: Report a bug or issue with the application
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below with as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the contributing guidelines
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you using?
      placeholder: "e.g., v1.2.3 or commit hash"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using? (Run `node --version`)
      placeholder: "e.g., v18.16.0"

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Are there any errors in the browser console or terminal?
      placeholder: Paste any error messages or stack traces here...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images or videos here, or paste URLs...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution (Optional)
      description: If you have ideas on how to fix the issue, please describe them here
      placeholder: Describe any potential solutions or workarounds...
